pub(super) fn for_page(page: &str) -> Option<&'static [&'static str]> {
    Some(match page {
        "context-menu" => &[
            "編集器右クリック",
            "explorer 空領域",
            "tab bar",
            "message 行",
            "leading icon + shortcut",
        ],
        "banner" => &[
            "保存失敗",
            "adapter 未接続",
            "添付サイズ超過",
            "成功通知",
            "details 展開",
            "title 表示",
            "leading icon",
            "sticky placement",
        ],
        "toast-stack-manager" => &[
            "位置 6 種類",
            "dedup ById",
            "pause_on_hover",
            "queue 上限超過",
            "action 付き toast",
        ],
        "tabs" => &[
            "workspace tabs",
            "add close",
            "pin lock",
            "move reorder",
            "grouped tabs",
            "overflow menu",
            "active follow",
            "icon",
            "dirty",
            "closeable",
            "tone",
            "tooltip",
            "a11y label",
            "group color",
            "group collapse",
            "overflow width",
            "group auto expand",
        ],
        "toolbar" => &[
            "overflow menu",
            "split action",
            "display mode",
            "density",
            "accelerator",
            "context anchor",
            "action priority",
            "action accelerator",
            "action split",
            "action group",
            "action tooltip",
            "action a11y",
            "action disabled",
            "group label",
            "group divider",
            "split disabled",
            "split tooltip",
            "split a11y",
        ],
        "breadcrumb" => &["trail", "click", "overflow", "theme crumb"],
        "accordion" => &[
            "closed",
            "open",
            "disabled",
            "controlled",
            "multiple",
            "tree mode",
            "reduced motion",
            "trigger areas",
        ],
        "split-pane" => &[
            "axis vertical",
            "wide gap",
            "center alignment",
            "overflow scroll",
            "ratio percent",
            "min percent clamp",
            "max percent clamp",
            "reset percent",
            "wide handle",
            "keyboard resize mode",
        ],
        "modal" => &[
            "native window",
            "escape close",
            "focus return",
            "parent block",
            "title footer size",
        ],
        "modal-overlay" => &[
            "overlay dialog",
            "backdrop close",
            "escape close",
            "focus trap",
            "dismiss disabled",
        ],
        "notification-toast" => &["toast", "dismiss", "ToastStackManager", "theme toast"],
        "popover" => &[
            "anchor",
            "placement",
            "auto flip",
            "offset width",
            "outside+escape close",
            "focus handling",
            "slot content",
        ],
        "hover-card" => &[
            "delayed open",
            "pointer follow",
            "focus trigger",
            "rich content",
            "actions",
        ],
        "color-picker-rgba" => &[
            "rgba value",
            "string value",
            "open panel",
            "hue slider",
            "alpha slider",
            "blend mode",
            "color plane",
            "trigger size",
            "title text",
            "rgb mode",
            "panel scale",
            "trigger border",
            "eyedropper action",
            "readonly block",
            "disabled block",
        ],
        "code-diff" => &[
            "mode split",
            "whitespace visible",
            "direction vertical",
            "context collapsed",
            "item count compact",
            "scroll sync off",
            "markdown language",
        ],
        "command-palette" => &[
            "command palette",
            "search results",
            "slash launcher",
            "disabled rows",
            "virtualized results",
            "Virtualization",
        ],
        "dynamic-array-editor" => &["rows", "add remove", "reorder", "theme row"],
        "selection-list" => &["items", "select", "multi", "theme list", "Virtualization"],
        "side-menu" => &["nav tree", "select", "collapse", "theme side"],
        "status-bar" => &[
            "editor status bar",
            "chat usage bar",
            "linter summary",
            "progress segment",
            "popover segment",
            "single message",
            "severity tone",
            "dismiss action",
            "segment a11y",
        ],
        "shortcut-combo" => &[
            "macOS",
            "Windows",
            "Linux",
            "custom separator",
            "a11y label",
        ],
        "shortcut-cheatsheet" => &[
            "cheatsheet sample",
            "カテゴリ filter",
            "two column",
            "one column",
            "select combo",
            "label",
            "groups",
            "group title",
            "items",
            "item combo",
        ],
        "settings-list" => &[
            "app settings",
            "chat settings",
            "lint settings",
            "dirty 表示",
            "query filter",
            "reset",
            "label",
            "section label",
            "section description",
            "section icon",
            "field count",
            "section footer",
            "section collapse",
            "default collapsed",
            "field label",
            "field description",
            "control options",
            "custom control",
            "set value",
        ],
        "collapsible-panel" => &[
            "Explorer panel",
            "Chat history panel",
            "TOC panel",
            "Floating overlay",
            "IconOnly",
        ],
        "virtualization" => &[
            "viewport offset",
            "overscan",
            "variable rows",
            "focused sentinel",
            "measured correction",
        ],
        "skeleton-cluster" => &[
            "list loading",
            "message loading",
            "card loading",
            "paragraph loading",
            "code block loading",
            "image card loading",
        ],
        "motion" => &[
            "4 primitive",
            "reduced-motion respect",
            "force ignore",
            "per-molecule motion",
        ],
        "window-control-button-group" => &[
            "macOS",
            "Windows",
            "Linux",
            "fullscreen hover",
            "close only",
        ],
        "startup-state-panel" => &[
            "app boot",
            "session init",
            "update install",
            "error retry",
            "cancel action",
        ],
        "tree-view" => &[
            "folders",
            "toggle",
            "context",
            "theme tree",
            "Virtualization",
        ],
        "drag-and-drop" => &[
            "reorder list",
            "file drop",
            "tab reorder",
            "attachment drop",
            "keyboard drag",
        ],
        "closeable-tab-strip" => &[
            "tab row default",
            "overflow",
            "pinned",
            "groups",
            "dirty",
            "dragging",
        ],
        "row" => &["row layout", "align", "overflow", "theme gap"],
        "column" => &["column", "align", "overflow", "theme gap"],
        "stack" => &["stacked", "z order", "overlay", "theme stack"],
        "grid" => &["grid cells", "span", "overflow", "theme grid"],
        "scroll-area" => &["viewport", "scroll", "scrollbar", "theme scroll"],
        "align-center" => &["center box", "baseline", "mixed text", "theme align"],
        _ => return super::preset_label_extra_feedback::for_page(page),
    })
}
