[workspace]
members = [
    "crates/katana-ui-core",
    "crates/katana-ui-core-egui",
    "crates/katana-ui-core-floem",
    "crates/katana-ui-core-gpui",
    "crates/katana-ui-core-storybook",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/HiroyukiFuruno/katana-ui-core"
rust-version = "1.95.0"
authors = ["Hiroyuki Furuno"]

[workspace.dependencies]
floem = { version = "0.2.0", git = "https://github.com/lapce/floem.git", rev = "ec7ea2077cf867e58e9684209291881217023f74" }
floem_reactive = { version = "0.2.0", git = "https://github.com/lapce/floem.git", rev = "ec7ea2077cf867e58e9684209291881217023f74" }
floem_renderer = { version = "0.2.0", git = "https://github.com/lapce/floem.git", rev = "ec7ea2077cf867e58e9684209291881217023f74" }
katana-ui-core = { version = "0.1.0", path = "crates/katana-ui-core" }
katana-ui-core-egui = { version = "0.1.0", path = "crates/katana-ui-core-egui" }
katana-ui-core-floem = { version = "0.1.0", path = "crates/katana-ui-core-floem" }
katana-ui-core-gpui = { version = "0.1.0", path = "crates/katana-ui-core-gpui" }
cosmic-text = "0.12.1"
image = { version = "0.25.10", default-features = false, features = ["png"] }
minifb = "0.28.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
