use super::{StorybookInteractionSpec, spec};

pub(super) fn for_page(page: &str) -> Option<StorybookInteractionSpec> {
    match page {
        "card" => Some(spec(
            "card_click",
            "card_activated",
            "interaction.active",
            "true",
            "active=true",
        )),
        "list" => Some(spec(
            "list_select",
            "selection_changed",
            "interaction.selected_index",
            "1",
            "selected=1",
        )),
        "menu" => Some(spec(
            "menu_open",
            "menu_opened",
            "interaction.open",
            "true",
            "open=true",
        )),
        "context-menu" => Some(spec(
            "context_menu_open",
            "context_menu_opened",
            "context_menu.anchor",
            "Pointer(192,128)",
            "context_menu=open",
        )),
        "banner" => Some(spec(
            "banner_toggle_details",
            "banner_details_toggled",
            "banner.details_open",
            "true",
            "details_open=true",
        )),
        "toast-stack-manager" => Some(spec(
            "toast_enqueue_visible",
            "toast_shown",
            "toast_stack.position",
            "BottomEnd",
            "visible=1",
        )),
        "tooltip" => Some(spec(
            "tooltip_hover",
            "tooltip_opened",
            "interaction.hovered",
            "true",
            "hover=true",
        )),
        "modal" => Some(spec(
            "modal_escape",
            "modal_closed",
            "interaction.open",
            "false",
            "open=false",
        )),
        "tabs" => Some(spec(
            "add_tab",
            "closeable_tab_added",
            "tabs.add",
            "notes.md",
            "tabs=6 active=notes.md",
        )),
        "toolbar" => Some(spec(
            "tool_toggle",
            "tool_changed",
            "interaction.active",
            "true",
            "active=true",
        )),
        "form-field" => Some(spec(
            "field_validate",
            "validation_changed",
            "invalid",
            "true",
            "invalid=true",
        )),
        "breadcrumb" => Some(spec(
            "breadcrumb_click",
            "route_changed",
            "interaction.selected_index",
            "2",
            "route=2",
        )),
        "accordion" => Some(spec(
            "accordion_toggle",
            "accordion_changed",
            "interaction.open",
            "false",
            "open=false",
        )),
        "code-diff" => Some(spec(
            "diff_mode_switch",
            "diff_mode_changed",
            "interaction.value",
            "Split",
            "mode=split",
        )),
        "color-picker-rgba" => Some(spec(
            "color_drag",
            "rgba_changed",
            "color_swatch.selected_color",
            "rgba(64,128,255,204)",
            "rgba=accent",
        )),
        "combo-box" => Some(spec(
            "combo_select",
            "combo_selected",
            "interaction.selected_index",
            "1",
            "selected=1",
        )),
        "command-palette" => Some(spec(
            "command_query_changed",
            "command_result_highlighted",
            "interaction.value",
            "theme",
            "highlighted=theme",
        )),
        "search-control-strip" => Some(spec(
            "search_query_changed",
            "search_query_changed",
            "search_control.query",
            "heading",
            "regex=true",
        )),
        "dynamic-array-editor" => Some(spec(
            "array_add",
            "array_changed",
            "interaction.value",
            "3 rows",
            "rows=3",
        )),
        "menu-button" => Some(spec(
            "menu_button_open",
            "menu_button_opened",
            "interaction.open",
            "true",
            "open=true",
        )),
        "modal-overlay" => Some(spec(
            "overlay_close",
            "overlay_closed",
            "interaction.open",
            "false",
            "open=false",
        )),
        "notification-toast" => Some(spec(
            "toast_dismiss",
            "toast_dismissed",
            "interaction.open",
            "false",
            "visible=false",
        )),
        "popover" => Some(spec(
            "popover_open",
            "popover_opened",
            "interaction.open",
            "true",
            "open=true",
        )),
        "hover-card" => Some(spec(
            "hover_card_open",
            "hover_card_opened",
            "interaction.open",
            "true",
            "open=true",
        )),
        "search-box" => Some(spec(
            "search_submit",
            "search_submitted",
            "text_entry.submit_on_enter",
            "true",
            "submitted=true",
        )),
        "segmented-toggle" => Some(spec(
            "segment_select",
            "segment_changed",
            "interaction.selected_index",
            "1",
            "segment=1",
        )),
        "select-box" => Some(spec(
            "select_option",
            "select_changed",
            "interaction.open",
            "false",
            "selected=true",
        )),
        "selection-list" => Some(spec(
            "selection_toggle",
            "selection_changed",
            "interaction.selected_index",
            "2",
            "selected=2",
        )),
        "side-menu" => Some(spec(
            "side_menu_select",
            "route_changed",
            "interaction.selected_index",
            "1",
            "route=1",
        )),
        "status-bar" => Some(spec(
            "status_bar_segment_popover",
            "status_bar_popover_opened",
            "status_bar.open_popover",
            "branch",
            "open_popover=branch",
        )),
        "shortcut-combo" => Some(spec(
            "shortcut_platform_preview",
            "shortcut_display_changed",
            "shortcut.platform",
            "MacOS",
            "combo=Command+K",
        )),
        "shortcut-cheatsheet" => Some(spec(
            "shortcut_filter_select",
            "shortcut_selected",
            "shortcut.query",
            "format",
            "selected=format",
        )),
        "settings-list" => Some(spec(
            "settings_filter_update_collapse",
            "settings_field_changed",
            "settings.query",
            "font",
            "dirty=font-size",
        )),
        "attachment-chip" => Some(spec(
            "attachment_status",
            "attachment_status_changed",
            "attachment.status",
            "Error",
            "status=error",
        )),
        "chip-group" => Some(spec(
            "chip_group_overflow",
            "chip_group_overflow_opened",
            "chip_group.overflow",
            "Menu",
            "overflow=open",
        )),
        "diagnostics-list" => Some(spec(
            "diagnostic_fix_preview",
            "diagnostic_fix_preview_toggled",
            "diagnostics.group_by",
            "Severity",
            "preview=true",
        )),
        "empty-state" => Some(spec(
            "empty_state_primary",
            "empty_state_actioned",
            "empty_state.primary_action",
            "reload",
            "action=reload",
        )),
        "tree-view" => Some(spec(
            "tree_click_toggle",
            "tree_toggled",
            "interaction.open",
            "false",
            "open=false",
        )),
        "drag-and-drop" => Some(spec(
            "drag_over",
            "drag_over",
            "drop_indicator.kind",
            "after",
            "dragging=true",
        )),
        "closeable-tab-strip" => Some(spec(
            "select_tab",
            "closeable_tab_selected",
            "active_tab_id",
            "settings",
            "active=settings",
        )),
        _ => None,
    }
}
