use super::{StorybookInteractionSpec, spec};

pub(super) fn for_page(page: &str) -> Option<StorybookInteractionSpec> {
    match page {
        "theme-tokens" => Some(spec(
            "theme_switch",
            "theme_changed",
            "theme_id",
            "light",
            "theme=light",
        )),
        "text" => Some(spec(
            "style_apply",
            "text_style_changed",
            "text.role",
            "heading",
            "role=heading",
        )),
        "icon" => Some(spec(
            "icon_select",
            "icon_changed",
            "icon.svg_source",
            "custom-svg",
            "svg=custom",
        )),
        "chip" => Some(spec(
            "chip_dismiss",
            "chip_dismissed",
            "chip.dismissible",
            "true",
            "dismissed=true",
        )),
        "loading-dots" => Some(spec(
            "animation_tick",
            "loading_phase_changed",
            "loading.reduced_motion",
            "true",
            "phase=1",
        )),
        "spinner" => Some(spec(
            "spinner_tick",
            "spinner_phase_changed",
            "loading.animation_state",
            "Paused",
            "phase=paused",
        )),
        "progress-bar" => Some(spec(
            "progress_change",
            "progress_changed",
            "progress.percent",
            "64",
            "percent=64",
        )),
        "button" => Some(spec(
            "button_press",
            "button_clicked",
            "variant",
            "Outline",
            "pressed=true",
        )),
        "text-button" => Some(spec(
            "text_button_press",
            "text_button_clicked",
            "tone",
            "Danger",
            "pressed=true",
        )),
        "svg-button" => Some(spec(
            "svg_button_press",
            "svg_button_clicked",
            "variant",
            "Icon",
            "pressed=true",
        )),
        "icon-text-button" => Some(spec(
            "icon_text_button_press",
            "icon_text_button_clicked",
            "button.icon_position",
            "trailing",
            "pressed=true",
        )),
        "text-input" => Some(spec(
            "input_commit",
            "text_committed",
            "interaction.value",
            "typed 日本語",
            "value=typed",
        )),
        "text-area" => Some(spec(
            "text_area_type",
            "text_area_changed",
            "text_area.auto_grow",
            "true",
            "rows=auto",
        )),
        "checkbox" => Some(spec(
            "checkbox_toggle",
            "checked_changed",
            "checked",
            "true",
            "checked=true",
        )),
        "radio" => Some(spec(
            "radio_select",
            "radio_selected",
            "checked",
            "true",
            "selected=true",
        )),
        "badge" => Some(spec(
            "badge_dismiss",
            "badge_dismissed",
            "status.severity",
            "Danger",
            "dismissed=true",
        )),
        "divider" => Some(spec(
            "divider_resize",
            "divider_changed",
            "size",
            "Inset",
            "inset=true",
        )),
        "spacer" => Some(spec(
            "spacer_resize",
            "spacer_changed",
            "size",
            "Large",
            "gap=large",
        )),
        "key-cap" => Some(spec(
            "shortcut_detect",
            "shortcut_matched",
            "shortcut.platform",
            "macos",
            "platform=macos",
        )),
        "color-swatch" => Some(spec(
            "color_select",
            "color_changed",
            "color_swatch.selected_color",
            "rgba(64,128,255,1)",
            "color=accent",
        )),
        "toggle" => Some(spec(
            "toggle_change",
            "toggle_changed",
            "checked",
            "true",
            "checked=true",
        )),
        "slide-control" => Some(spec(
            "slide_drag",
            "slide_changed",
            "interaction.value",
            "64",
            "value=64",
        )),
        _ => None,
    }
}
