use super::LegacyPageContract;

macro_rules! contract {
    ($number:expr, $label:expr, $page:expr, $action:expr, $event:expr, $option:expr, $after:expr, $state:expr, $preset:expr $(,)?) => {
        LegacyPageContract {
            number: $number,
            label: $label,
            page: $page,
            action: $action,
            event: $event,
            option: $option,
            after: $after,
            state: $state,
            preset: $preset,
        }
    };
}

pub(super) const CONTRACTS: &[LegacyPageContract] = &[
    contract!(
        13,
        "SearchBox",
        "search-box",
        "search_submit",
        "search_submitted",
        "text_entry.submit_on_enter",
        "true",
        "submitted=true",
        "regex case",
    ),
    contract!(
        14,
        "Tooltip",
        "tooltip",
        "tooltip_hover",
        "tooltip_opened",
        "interaction.hovered",
        "true",
        "hover=true",
        "placement edge",
    ),
    contract!(
        15,
        "Badge",
        "badge",
        "badge_passive",
        "none",
        "status.severity",
        "Danger",
        "use Chip for dismiss",
        "tone grid",
    ),
    contract!(
        16,
        "KeyCap",
        "key-cap",
        "shortcut_detect",
        "shortcut_matched",
        "shortcut.platform",
        "macos",
        "platform=macos",
        "combo",
    ),
    contract!(
        17,
        "Card",
        "card",
        "card_click",
        "card_activated",
        "interaction.active",
        "true",
        "active=true",
        "nested controls",
    ),
    contract!(
        18,
        "Accordion",
        "accordion",
        "accordion_toggle",
        "accordion_changed",
        "interaction.open",
        "false",
        "open=false",
        "trigger areas",
    ),
    contract!(
        19,
        "SplitPane",
        "split-pane",
        "split_drag",
        "split_ratio_changed",
        "interaction.value",
        "0.64",
        "ratio=0.64",
        "min percent clamp",
    ),
    contract!(
        20,
        "Modal",
        "modal",
        "modal_escape",
        "modal_closed",
        "interaction.open",
        "false",
        "open=false",
        "focus return",
    ),
    contract!(
        20,
        "ModalOverlay",
        "modal-overlay",
        "overlay_close",
        "overlay_closed",
        "interaction.open",
        "false",
        "open=false",
        "focus trap",
    ),
    contract!(
        21,
        "Popover",
        "popover",
        "popover_open",
        "popover_opened",
        "interaction.open",
        "true",
        "open=true",
        "auto flip",
    ),
    contract!(
        22,
        "ColorPicker",
        "color-picker-rgba",
        "color_drag",
        "rgba_changed",
        "color_swatch.selected_color",
        "rgba(64,128,255,204)",
        "rgba=accent",
        "rgba value",
    ),
    contract!(
        23,
        "ColorPicker parity",
        "color-picker-rgba",
        "color_drag",
        "rgba_changed",
        "color_swatch.selected_color",
        "rgba(64,128,255,204)",
        "rgba=accent",
        "disabled block",
    ),
    contract!(
        24,
        "CodeDiff",
        "code-diff",
        "diff_mode_switch",
        "diff_mode_changed",
        "interaction.value",
        "Split",
        "mode=split",
        "markdown language",
    ),
];
