use super::LegacyPageContract;

macro_rules! contract {
    ($number:expr, $label:expr, $page:expr, $action:expr, $event:expr, $option:expr, $after:expr, $state:expr, $preset:expr $(,)?) => {
        LegacyPageContract {
            number: $number,
            label: $label,
            page: $page,
            action: $action,
            event: $event,
            option: $option,
            after: $after,
            state: $state,
            preset: $preset,
        }
    };
}

pub(super) const CONTRACTS: &[LegacyPageContract] = &[
    contract!(
        1,
        "Theme / Panel theme",
        "theme-tokens",
        "theme_switch",
        "theme_changed",
        "theme.id",
        "light",
        "theme=light",
        "dark palette",
    ),
    contract!(
        2,
        "Text",
        "text",
        "style_apply",
        "text_style_changed",
        "text.role",
        "heading",
        "role=heading",
        "mixed script",
    ),
    contract!(
        3,
        "Icon",
        "icon",
        "icon_select",
        "icon_changed",
        "icon.svg_source",
        "custom-svg",
        "svg=custom",
        "custom SVG",
    ),
    contract!(
        4,
        "LoadingDots",
        "loading-dots",
        "animation_tick",
        "loading_phase_changed",
        "loading.reduced_motion",
        "true",
        "phase=1",
        "phase tick",
    ),
    contract!(
        4,
        "Spinner",
        "spinner",
        "spinner_tick",
        "spinner_phase_changed",
        "loading.animation_state",
        "Paused",
        "phase=paused",
        "phase tick",
    ),
    contract!(
        5,
        "SvgButton",
        "svg-button",
        "svg_button_press",
        "svg_button_clicked",
        "variant",
        "Icon",
        "pressed=true",
        "basic",
    ),
    contract!(
        6,
        "TextButton",
        "text-button",
        "text_button_press",
        "text_button_clicked",
        "tone",
        "Danger",
        "pressed=true",
        "classic",
    ),
    contract!(
        7,
        "IconTextButton",
        "icon-text-button",
        "icon_text_button_press",
        "icon_text_button_clicked",
        "button.icon_position",
        "trailing",
        "pressed=true",
        "dense",
    ),
    contract!(
        8,
        "Toggle",
        "toggle",
        "toggle_change",
        "toggle_changed",
        "checked",
        "true",
        "checked=true",
        "on action",
    ),
    contract!(
        9,
        "SegmentedToggle",
        "segmented-toggle",
        "segment_select",
        "segmented_toggle_selected",
        "interaction.selected_index",
        "1",
        "segment=1",
        "select action",
    ),
    contract!(
        10,
        "SelectBox",
        "select-box",
        "select_option",
        "select_box_selected",
        "interaction.open",
        "false",
        "selected=true",
        "selected index",
    ),
    contract!(
        11,
        "ColorSwatch",
        "color-swatch",
        "color_select",
        "color_changed",
        "color_swatch.selected_color",
        "rgba(64,128,255,1)",
        "color=accent",
        "select color",
    ),
    contract!(
        12,
        "TextInput",
        "text-input",
        "input_commit",
        "text_committed",
        "interaction.value",
        "typed 日本語",
        "value=typed",
        "ime event",
    ),
    contract!(
        12,
        "TextArea",
        "text-area",
        "text_area_type",
        "text_area_changed",
        "text_area.resize_enabled",
        "true",
        "resize=true",
        "resize handle",
    ),
];
