use super::rich_content::{PopoverArrowSpec, PopoverFocusManagement, PopoverSlots};
use crate::interaction::placement::Placement;
use crate::molecule::disclosure_foundation::DisclosureTriggerArea;
use crate::render_model::UiNodeId;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(super) struct DisclosureTypedModel {
    pub placement: String,
    pub offset: (i16, i16),
    pub outside_click_dismiss: bool,
    pub escape_dismiss: bool,
    pub anchor_summary: String,
    pub backdrop: String,
    pub focus_return: String,
    pub focus_return_target: Option<UiNodeId>,
    pub dismiss_policy: String,
    pub arrow: PopoverArrowSpec,
    pub slots: PopoverSlots,
    pub focus_management: PopoverFocusManagement,
    pub keep_open_on_inner_focus: bool,
    pub auto_flip_priority: Vec<Placement>,
    pub title: String,
    pub size: String,
    pub footer: String,
    pub native_window_mode: bool,
    pub width: String,
    pub focus_handling: String,
    pub delay_ms: u16,
    pub max_width: u16,
    pub hover_trigger: bool,
    pub focus_trigger: bool,
    pub timer_summary: String,
    pub controlled: bool,
    pub multiple: bool,
    pub indicator_position: String,
    pub trigger_area: DisclosureTriggerArea,
    pub toggle_icon: String,
    pub tree_mode: bool,
    pub reduced_motion: bool,
    pub body_border: bool,
    pub selected: bool,
    pub depth: u8,
    pub show_lines: bool,
    pub minimum: i32,
    pub maximum: i32,
    pub step: i32,
    pub binding: String,
}

impl Default for DisclosureTypedModel {
    fn default() -> Self {
        Self {
            placement: String::new(),
            offset: (0, 0),
            outside_click_dismiss: false,
            escape_dismiss: false,
            anchor_summary: String::new(),
            backdrop: String::new(),
            focus_return: String::new(),
            focus_return_target: None,
            dismiss_policy: String::new(),
            arrow: PopoverArrowSpec::default(),
            slots: PopoverSlots::default(),
            focus_management: PopoverFocusManagement::default(),
            keep_open_on_inner_focus: false,
            auto_flip_priority: Vec::new(),
            title: String::new(),
            size: String::new(),
            footer: String::new(),
            native_window_mode: false,
            width: String::new(),
            focus_handling: String::new(),
            delay_ms: 0,
            max_width: 0,
            hover_trigger: false,
            focus_trigger: false,
            timer_summary: String::new(),
            controlled: false,
            multiple: false,
            indicator_position: String::new(),
            trigger_area: DisclosureTriggerArea::default(),
            toggle_icon: String::new(),
            tree_mode: false,
            reduced_motion: false,
            body_border: false,
            selected: false,
            depth: 0,
            show_lines: false,
            minimum: 0,
            maximum: 100,
            step: 1,
            binding: String::new(),
        }
    }
}
