use super::{LegacyDodSpec, spec};

pub(super) const MOLECULE_SPECS: &[LegacyDodSpec] = &[
    spec(
        "select-box",
        "10-select-box",
        "interaction.open",
        "bool",
        "false",
        ["trigger", "select-action", "long-list", "theme-panel"],
    ),
    spec(
        "color-swatch",
        "11-color-swatch",
        "color_swatch.selected_color",
        "ColorToken",
        "rgba(64,128,255,1)",
        ["palette", "select-color", "disabled", "theme-ring"],
    ),
    spec(
        "text-input",
        "12-text-input",
        "interaction.value",
        "String",
        "typed 日本語 🔷",
        ["value", "ime-event", "invalid", "theme-slot"],
    ),
    spec(
        "search-box",
        "13-search-box",
        "text_entry.submit_on_enter",
        "bool",
        "true",
        ["search-icon", "submit-action", "regex-case", "theme-clear"],
    ),
    spec(
        "tooltip",
        "14-tooltip",
        "interaction.hovered",
        "bool",
        "true",
        ["anchor", "hover-open", "placement-edge", "theme-overlay"],
    ),
    spec(
        "badge",
        "15-badge",
        "status.severity",
        "UiTone",
        "Danger",
        ["tone-grid", "passive-status", "small-size", "theme-badge"],
    ),
    spec(
        "key-cap",
        "16-key-cap",
        "shortcut.platform",
        "Platform",
        "macos",
        ["single-key", "combo", "non-macos", "theme-key"],
    ),
    spec(
        "card",
        "17-card",
        "interaction.active",
        "bool",
        "true",
        ["slots", "card-click", "nested-controls", "theme-border"],
    ),
    spec(
        "accordion",
        "18-accordion",
        "interaction.open",
        "bool",
        "false",
        [
            "header-body",
            "toggle-action",
            "tree-mode",
            "theme-indicator",
        ],
    ),
    spec(
        "split-pane",
        "19-split-pane",
        "interaction.value",
        "Ratio",
        "0.64",
        ["horizontal", "drag-action", "min-clamp", "theme-handle"],
    ),
    spec(
        "modal",
        "20-modal",
        "interaction.open",
        "bool",
        "false",
        ["dialog", "escape-close", "focus-trap", "theme-overlay"],
    ),
    spec(
        "modal-overlay",
        "20-modal-overlay",
        "interaction.open",
        "bool",
        "false",
        [
            "overlay-dialog",
            "backdrop-close",
            "focus-return",
            "theme-overlay",
        ],
    ),
    spec(
        "popover",
        "21-popover",
        "interaction.open",
        "bool",
        "false",
        ["anchor", "outside-close", "placement-edge", "theme-shadow"],
    ),
    spec(
        "color-picker-rgba",
        "22-color-picker",
        "color_swatch.selected_color",
        "RgbaColor",
        "rgba(64,128,255,204)",
        ["rgba-panel", "drag-plane", "alpha-edge", "theme-preview"],
    ),
    spec(
        "color-picker-rgba",
        "23-color-picker-parity",
        "color_picker.trigger_size",
        "TriggerSize",
        "large",
        [
            "color-only-trigger",
            "floating-panel",
            "seamless-hue",
            "theme-trigger",
        ],
    ),
    spec(
        "code-diff",
        "24-code-diff",
        "interaction.value",
        "DiffMode",
        "Split",
        ["inline", "mode-switch", "collapsed", "theme-japanese"],
    ),
    spec(
        "attachment-chip",
        "07-attachment-chip",
        "interaction.value",
        "AttachmentStatus",
        "Error",
        ["file", "image", "url", "uploading"],
    ),
    spec(
        "chip-group",
        "07-chip-group",
        "interaction.open",
        "bool",
        "true",
        ["wrap", "overflow-menu", "horizontal-scroll", "reorder"],
    ),
];
