fn motion_catalogue() -> Vec<(
    FullTextCommandSurfaceScenarioId,
    FullTextCommandSurfaceRawInputStage,
    SelectionMotionTransition,
    FindMotionTransition,
    DropdownMotionTransition,
)> {
    let mut catalogue = Vec::new();
    let scenario_id = FullTextCommandSurfaceScenarioId::Resting;
    catalogue.extend(stages(scenario_id).into_iter().map(|stage| {
        (
            scenario_id,
            stage,
            SelectionMotionTransition::None,
            FindMotionTransition::None,
            DropdownMotionTransition::None,
        )
    }));
    let find_stage = stage(Vec::new(), 1.0);
    catalogue.push((
        FullTextCommandSurfaceScenarioId::Find,
        find_stage.clone(),
        SelectionMotionTransition::None,
        FindMotionTransition::Begin,
        DropdownMotionTransition::None,
    ));
    catalogue.extend(std::iter::repeat_n(
        (
            FullTextCommandSurfaceScenarioId::Find,
            find_stage,
            SelectionMotionTransition::None,
            FindMotionTransition::Advance,
            DropdownMotionTransition::None,
        ),
        FIND_ADVANCE_COUNT,
    ));
    for scenario_id in [
        FullTextCommandSurfaceScenarioId::Context,
        FullTextCommandSurfaceScenarioId::Readonly,
        FullTextCommandSurfaceScenarioId::ResizeScrollIme,
        FullTextCommandSurfaceScenarioId::NavigationInput,
        FullTextCommandSurfaceScenarioId::WorkspaceTabs,
    ] {
        catalogue.extend(stages(scenario_id).into_iter().map(|stage| {
            (
                scenario_id,
                stage,
                SelectionMotionTransition::None,
                FindMotionTransition::None,
                DropdownMotionTransition::None,
            )
        }));
    }
    let dropdown_stage = stage(Vec::new(), 1.0);
    catalogue.extend([
        (
            FullTextCommandSurfaceScenarioId::Resting,
            dropdown_stage.clone(),
            SelectionMotionTransition::None,
            FindMotionTransition::None,
            DropdownMotionTransition::BeginTrigger,
        ),
        (
            FullTextCommandSurfaceScenarioId::Resting,
            dropdown_stage.clone(),
            SelectionMotionTransition::None,
            FindMotionTransition::None,
            DropdownMotionTransition::Advance,
        ),
        (
            FullTextCommandSurfaceScenarioId::Resting,
            dropdown_stage.clone(),
            SelectionMotionTransition::None,
            FindMotionTransition::None,
            DropdownMotionTransition::Advance,
        ),
        (
            FullTextCommandSurfaceScenarioId::Resting,
            dropdown_stage.clone(),
            SelectionMotionTransition::None,
            FindMotionTransition::None,
            DropdownMotionTransition::Advance,
        ),
        (
            FullTextCommandSurfaceScenarioId::Resting,
            dropdown_stage.clone(),
            SelectionMotionTransition::None,
            FindMotionTransition::None,
            DropdownMotionTransition::BeginItem,
        ),
        (
            FullTextCommandSurfaceScenarioId::Resting,
            dropdown_stage.clone(),
            SelectionMotionTransition::None,
            FindMotionTransition::None,
            DropdownMotionTransition::Advance,
        ),
        (
            FullTextCommandSurfaceScenarioId::Resting,
            dropdown_stage.clone(),
            SelectionMotionTransition::None,
            FindMotionTransition::None,
            DropdownMotionTransition::Advance,
        ),
        (
            FullTextCommandSurfaceScenarioId::Resting,
            dropdown_stage.clone(),
            SelectionMotionTransition::None,
            FindMotionTransition::None,
            DropdownMotionTransition::Advance,
        ),
        (
            FullTextCommandSurfaceScenarioId::Resting,
            dropdown_stage,
            SelectionMotionTransition::None,
            FindMotionTransition::None,
            DropdownMotionTransition::None,
        ),
    ]);
    let selection_stage = stage(Vec::new(), 1.0);
    catalogue.insert(
        1,
        (
            FullTextCommandSurfaceScenarioId::Selection,
            selection_stage.clone(),
            SelectionMotionTransition::Begin,
            FindMotionTransition::None,
            DropdownMotionTransition::None,
        ),
    );
    catalogue.splice(
        2..2,
        std::iter::repeat_n(
            (
                FullTextCommandSurfaceScenarioId::Selection,
                selection_stage,
                SelectionMotionTransition::Advance,
                FindMotionTransition::None,
                DropdownMotionTransition::None,
            ),
            SELECTION_ADVANCE_COUNT,
        ),
    );
    catalogue.push((
        FullTextCommandSurfaceScenarioId::Resting,
        stage(Vec::new(), 1.0),
        SelectionMotionTransition::None,
        FindMotionTransition::None,
        DropdownMotionTransition::None,
    ));
    catalogue
}
